name: vectorquant-snowflake
channels:
  - conda-forge
  - snowflake
  - defaults
dependencies:
  - python=3.9
  - streamlit>=1.28.0
  - plotly>=5.17.0
  - pandas>=1.5.0
  - numpy>=1.21.0
  - snowflake-connector-python>=3.0.0
  - snowflake-sqlalchemy>=1.4.0
  - sqlalchemy>=1.4.0
  - requests>=2.28.0
  - python-dotenv>=0.19.0
  - cryptography>=3.4.8
  - pyarrow>=10.0.0
  - fastapi>=0.100.0
  - uvicorn>=0.23.0
  - pydantic>=2.0.0
  - python-multipart>=0.0.6
  - pip
  - pip:
    - streamlit-snowflake>=0.1.0
    - streamlit-aggrid>=0.3.0
    - streamlit-plotly-events>=0.0.6
